# Generated by Django 5.1.4 on 2024-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto_aluno',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto_evento',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
